!!>
!!> \section{Subroutine \texttt{welcome}}
!!>
!!> This subroutine display program welcome message which is printed at the
!!> beginning of running program.
!!>
!!> Currently it will output the following
!!> \begin{itemize}
!!> \item "LFDFT" text which is pregenerated by \texttt{figlet}. The font used is
!!>       is differentiated according to the specific compiler used to build
!!>       the program. Currently there are five variants. The compilers
!!>       did not treat the Figlet string (\texttt{CHARACTER(*)}) output
!!>       in the same way.
!!> \item Printing the current time for reference as the time program start.
!!> \item Compiler name used to build the program.
!!> \end{itemize}
!!>
SUBROUTINE welcome()
  IMPLICIT NONE

!!> The following texts are generated using \texttt{figlet} program.
!!> Not all compilers have support to correctly display the characters
!!> used in the figlet output.

WRITE(*,*)
WRITE(*,*) "ffr's program starts"
WRITE(*,*)

#ifdef __G95__
WRITE(*,*) "=================================="
WRITE(*,*) "    __    __________  ____________"
WRITE(*,*) "   / /   / ____/ __ \/ ____/_  __/"
WRITE(*,*) "  / /   / /_  / / / / /_    / /"
WRITE(*,*) " / /___/ __/ / /_/ / __/   / /"
WRITE(*,*) "/_____/_/   /_____/_/     /_/"
WRITE(*,*) "=================================="
#endif


! DOS Rebel
#ifdef __SUNPRO_F95
WRITE(*,*) "$$\       $$$$$$$$\ $$$$$$$\  $$$$$$$$\ $$$$$$$$\ "
WRITE(*,*) "$$ |      $$  _____|$$  __$$\ $$  _____|\__$$  __|"
WRITE(*,*) "$$ |      $$ |      $$ |  $$ |$$ |         $$ |   "
WRITE(*,*) "$$ |      $$$$$\    $$ |  $$ |$$$$$\       $$ |   "
WRITE(*,*) "$$ |      $$  __|   $$ |  $$ |$$  __|      $$ |   "
WRITE(*,*) "$$ |      $$ |      $$ |  $$ |$$ |         $$ |   "
WRITE(*,*) "$$$$$$$$\ $$ |      $$$$$$$  |$$ |         $$ |   "
WRITE(*,*) "\________|\__|      \_______/ \__|         \__|   "
#endif

#ifdef __PGI
WRITE(*,*) " █████       ███████████ ██████████   ███████████ ███████████"
WRITE(*,*) "░░███       ░░███░░░░░░█░░███░░░░███ ░░███░░░░░░█░█░░░███░░░█"
WRITE(*,*) " ░███        ░███   █ ░  ░███   ░░███ ░███   █ ░ ░   ░███  ░ "
WRITE(*,*) " ░███        ░███████    ░███    ░███ ░███████       ░███    "
WRITE(*,*) " ░███        ░███░░░█    ░███    ░███ ░███░░░█       ░███    "
WRITE(*,*) " ░███      █ ░███  ░     ░███    ███  ░███  ░        ░███    "
WRITE(*,*) " ███████████ █████       ██████████   █████          █████   "
WRITE(*,*) "░░░░░░░░░░░ ░░░░░       ░░░░░░░░░░   ░░░░░          ░░░░░    "
#endif

#ifdef __INTEL_COMPILER
WRITE(*,*) "**************************************************************"
WRITE(*,*) "*   _____       _________   ______     _________   ________  *"
WRITE(*,*) "*  (_   _)     (_   _____) (_  __ \   (_   _____) (___  ___) *"
WRITE(*,*) "*   | |         ) (___      ) ) \ \    ) (___        ) )     *"
WRITE(*,*) "*   | |        (   ___)    ( (   ) )  (   ___)      ( (      *"
WRITE(*,*) "*   | |   __    ) (         ) )  ) )   ) (           ) )     *"
WRITE(*,*) "* __| |___) )  (   )       / /__/ /   (   )         ( (      *"
WRITE(*,*) "* \________/    \_/       (______/     \_/          /__\     *"
WRITE(*,*) "*                                                            *"
WRITE(*,*) "**************************************************************"
#endif


#ifdef __GFORTRAN__
WRITE(*,*) " .----------------.  .----------------.  .----------------.  .----------------.  .----------------."
WRITE(*,*) "| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |"
WRITE(*,*) "| |   _____      | || |  _________   | || |  ________    | || |  _________   | || |  _________   | |"
WRITE(*,*) "| |  |_   _|     | || | |_   ___  |  | || | |_   ___ `.  | || | |_   ___  |  | || | |  _   _  |  | |"
WRITE(*,*) "| |    | |       | || |   | |_  \_|  | || |   | |   `. \ | || |   | |_  \_|  | || | |_/ | | \_|  | |"
WRITE(*,*) "| |    | |   _   | || |   |  _|      | || |   | |    | | | || |   |  _|      | || |     | |      | |"
WRITE(*,*) "| |   _| |__/ |  | || |  _| |_       | || |  _| |___.' / | || |  _| |_       | || |    _| |_     | |"
WRITE(*,*) "| |  |________|  | || | |_____|      | || | |________.'  | || | |_____|      | || |   |_____|    | |"
WRITE(*,*) "| |              | || |              | || |              | || |              | || |              | |"
WRITE(*,*) "| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |"
WRITE(*,*) " '----------------'  '----------------'  '----------------'  '----------------'  '----------------'"
#endif

  CALL timestamp('Program started at')

  CALL compile_info()

END SUBROUTINE
